apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aiops-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aiops-agent.labels" . | nindent 4 }}
